version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase..
      - echo Build started on `date`
      - mvn clean package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/marketing*.jar
  discard-paths: yes

